[tool.towncrier]
package = "" # We have more than one package to manage...
name = ""    # ... so we leave these empty

directory = "changelog.d"
filename = "CHANGELOG.md"
start_string = "<!-- towncrier release notes start -->\n"
underlines = ["", "", ""]
title_format = "## {version} - {project_date}"
issue_format = "[#{issue}](https://github.com/PhotonicGluon/Excalibur/issues/{issue})"

[[tool.towncrier.type]]
directory = "security"
name = "ğŸ”’ Security"
showcontent = true

[[tool.towncrier.type]]
directory = "deprecated"
name = "âš ï¸ Deprecations"
showcontent = true

[[tool.towncrier.type]]
directory = "added"
name = "âœ¨ Additions"
showcontent = true

[[tool.towncrier.type]]
directory = "changed"
name = "âœï¸ Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "performance"
name = "ğŸš„ Performance Improvements"
showcontent = true

[[tool.towncrier.type]]
directory = "performance"
name = "Performance Improvements"
showcontent = true

[[tool.towncrier.type]]
directory = "fixed"
name = "ğŸ”§ Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "removed"
name = "ğŸ—‘ï¸ Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "internal"
name = "âš™ï¸ Internal"
showcontent = true
